In [1]:
%load_ext lab_black
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path
import numpy as np
from puzzle import Puzzle, Scanner, plot

In [70]:
puz = Puzzle("tests.txt")

s = puz.scanners[0]
s1 = puz.scanners[1]
s2 = puz.scanners[2]
s3 = puz.scanners[3]
s4 = puz.scanners[4]

In [71]:
s.beacons.shape

(25, 3)

In [113]:
def orient_to(scnzor, other):
    """Assumes other has already been centered w/ other.to_origin()"""
    scnzor.to_origin()

    am = scnzor.beacons
    bm = other.beacons
    H = am.T @ bm
    # print(H.shape)
    U, S, Vt = np.linalg.svd(H)
    # U = U  # .astype(int)
    # Vt = Vt  # .astype(int)

    d = np.sign(np.linalg.det(Vt.T @ U.T))
    correction = np.array([[1, 0, 0], [0, 1, 0], [0, 0, d]])

    R = Vt.T @ correction @ U.T

    t = -R @ scnzor.centroid + other.centroid
    print(t)
    return (R @ scnzor.beacons.T + t.reshape(3, -1)).astype(int).T


new_s1 = orient_to(s1, s)

new_s1

[-195.19396002   31.10102895  -18.95258948]


array([[  387,  -601,  -211],
       [  331,  -473,   -95],
       [  484,  -118,   744],
       [ -547, -1033,   131],
       [ -187,   -23,    60],
       [ -689, -1012,   150],
       [ -700,  1060,   129],
       [   28,  -290,  -862],
       [ -520,    67,   853],
       [  128,  -155,  -854],
       [  436,  -565,  -192],
       [-1076,    22,  -734],
       [ -545,  -894,   119],
       [ -852,  1077,    74],
       [ -965,  -101,  -648],
       [ -434,   127,   790],
       [  272,   825,  -308],
       [ -889,     2,  -721],
       [  400,   -84,   825],
       [ -474,   101,   778],
       [   45,  -107,  -830],
       [ -774,  1206,    13],
       [  391,   987,  -245],
       [  373,   826,  -168],
       [  516,   -76,   727]])

In [108]:
def find_overlap(arr1, arr2):
    s = set(tuple(map(tuple, arr1)))
    othr = set(tuple(map(tuple, arr2)))
    return s & othr


find_overlap(s.beacons, new_s1)

set()

In [90]:
in_s = set(tuple(map(tuple, s.beacons)))
in_s1 = set(tuple(map(tuple, s1.beacons)))
in_s & in_s1

set()

In [88]:
s.beacons  # + s.centroid

array([[ 479, -584, -868],
       [ 603, -639,  442],
       [-763,  595,  767],
       [ 465, -671, -760],
       [-462, -819, -425],
       [-410, -353,  380],
       [-270, -307,  414],
       [-586, -812, -542],
       [-801,  653,  796],
       [-543, -820, -588],
       [ 628,  349, -534],
       [ 549,  584,  700],
       [-372, -325,  351],
       [-509,  872, -524],
       [ 619, -623, -857],
       [ 639,  396, -444],
       [ 530,  733,  761],
       [-817,  528,  717],
       [-614,  849, -497],
       [ 498, -697,  467],
       [  82,  -29,  -38],
       [ 705,  323, -346],
       [ 518,  584,  695],
       [-714,  904, -518],
       [ 534, -703,  434]])

In [8]:
s1.to_origin()
s1.beacons + s1.centroid

array([[ 686,  422,  578],
       [ 605,  423,  415],
       [ 515,  917, -361],
       [-336,  658,  858],
       [  95,  138,   22],
       [-476,  619,  847],
       [-340, -569, -846],
       [ 567, -361,  727],
       [-460,  603, -452],
       [ 669, -402,  600],
       [ 729,  430,  532],
       [-500, -761,  534],
       [-322,  571,  750],
       [-466, -666, -811],
       [-429, -592,  574],
       [-355,  545, -477],
       [ 703, -491, -529],
       [-328, -685,  520],
       [ 413,  935, -424],
       [-391,  539, -444],
       [ 586, -435,  557],
       [-364, -763, -893],
       [ 807, -499, -711],
       [ 755, -354, -619],
       [ 553,  889, -390]])

In [9]:
s.beacons

array([[ 479, -584, -868],
       [ 603, -639,  442],
       [-763,  595,  767],
       [ 465, -671, -760],
       [-462, -819, -425],
       [-410, -353,  380],
       [-270, -307,  414],
       [-586, -812, -542],
       [-801,  653,  796],
       [-543, -820, -588],
       [ 628,  349, -534],
       [ 549,  584,  700],
       [-372, -325,  351],
       [-509,  872, -524],
       [ 619, -623, -857],
       [ 639,  396, -444],
       [ 530,  733,  761],
       [-817,  528,  717],
       [-614,  849, -497],
       [ 498, -697,  467],
       [  82,  -29,  -38],
       [ 705,  323, -346],
       [ 518,  584,  695],
       [-714,  904, -518],
       [ 534, -703,  434]])

In [10]:
s1.beacons

array([[ 570,  378,  556],
       [ 489,  379,  393],
       [ 399,  873, -383],
       [-452,  614,  836],
       [ -21,   94,    0],
       [-592,  575,  825],
       [-456, -613, -868],
       [ 451, -405,  705],
       [-576,  559, -474],
       [ 553, -446,  578],
       [ 613,  386,  510],
       [-616, -805,  512],
       [-438,  527,  728],
       [-582, -710, -833],
       [-545, -636,  552],
       [-471,  501, -499],
       [ 587, -535, -551],
       [-444, -729,  498],
       [ 297,  891, -446],
       [-507,  495, -466],
       [ 470, -479,  535],
       [-480, -807, -915],
       [ 691, -543, -733],
       [ 639, -398, -641],
       [ 437,  845, -412]])

In [ ]:
s1.centroid

In [ ]:
#!/usr/bin/python

import numpy as np

# Input: expects 3xN matrix of points
# Returns R,t
# R = 3x3 rotation matrix
# t = 3x1 column vector


def rigid_transform_3D(A, B):
    """Copied from:
    https://github.com/nghiaho12/rigid_transform_3D/blob/master/rigid_transform_3D.py

    which was first discovered @ this blog:
    http://nghiaho.com/?page_id=671
    """
    assert A.shape == B.shape

    num_rows, num_cols = A.shape
    if num_rows != 3:
        raise Exception(f"matrix A is not 3xN, it is {num_rows}x{num_cols}")

    num_rows, num_cols = B.shape
    if num_rows != 3:
        raise Exception(f"matrix B is not 3xN, it is {num_rows}x{num_cols}")

    # find mean column wise
    centroid_A = np.mean(A, axis=1).astype(int).reshape(-1, 1)
    centroid_B = np.mean(B, axis=1).astype(int).reshape(-1, 1)

    # re-center on (0, 0, 0)
    Am = A - centroid_A
    Bm = B - centroid_B

    H = Am @ Bm.T

    # find rotation
    U, S, Vt = np.linalg.svd(H)
    Vt = Vt.astype(int)
    U = U.astype(int)
    R = Vt.T @ U.T

    # special reflection case
    if np.linalg.det(R) < 0:
        # print("det(R) < R, reflection detected!, correcting for it ...")
        Vt[2, :] *= -1
        R = Vt.T @ U.T

    t = -R @ centroid_A + centroid_B

    return R, t


A = s.beacons.T
B = s1.beacons.T

rot, shift = rigid_transform_3D(A, B)
tmp = rot @ A + B
tmp.T == B.T

In [ ]:
control = puz.scanners[0].beacons.T

transforms = {}

for scnr_num in range(1, len(puz.scanners)+1):
    other = puz.scanners[scnr_num].beacons.T
    transforms[(0, scnr_num)] = rigid_transform_3D(control, other)
    
transforms

In [ ]:
shift

In [ ]:
np.mean(A, axis=1).astype(int)

In [ ]:
control = puz.scanners[0]

for scnr in puz.scanners.values():
    scnr.orient_to(control)

In [ ]:
sum([scnr.done for scnr in puz.scanners.values()])

In [ ]:
s.reset().beacons

In [ ]:

s1.flip("x").rot90("x").flip("y")
s1.beacons

In [ ]:
set(s.hashable)

In [ ]:
seen = set()
seen.add(s.hashable)
seen

In [ ]:
s == s1

In [ ]:
seen = s1.orient_to(s)
len(seen)

In [ ]:
s1.flip("y")

In [ ]:
plot(s.beacons)

In [ ]:
set(s1.hashable)

In [ ]:
s.orient_to(s1)

In [ ]:
seen = set()
duplicated = []
i = 0
for axis in "xyz":
    for rot in [0, 1, 2, 3]:
        new = s.rot90(axis, rot)
        hashed = tuple(map(tuple, new))
        if hashed in seen:
            duplicated.append(new)
        seen.add(hashed)
        p = plot(new)
        p.title(f"{i}: {axis} : {rot * 90}")
        p.show()
        i += 1
    s.beacons = s.flip(axis)
    for rot in [0, 1, 2, 3]:
        new = s.rot90(axis, rot)
        hashed = tuple(map(tuple, new))
        if hashed in seen:
            duplicated.append(new)
        seen.add(hashed)
        p = plot(new)
        p.title(f"{i}: Flipped {axis} : {rot * 90}")
        p.show()
        i += 1
    s.beacons = s.flip(axis)

len(seen)

In [ ]:
for arr in duplicated:
    plot(arr)

In [ ]:
s.rot90("x")

In [ ]:
puz.scanners[0].flip("x")
# puz.scanners[0] == puz.scanners[1]

In [ ]:
puz.scanners[0].beacons

In [ ]:
scanner = puz.scanners[0]
scanner.beacons

In [ ]:
scanner.rot90("x")

In [ ]:
scanner.flip("z")

In [ ]:
puz.part_1()

In [ ]:
puz.part_2()

## Black format my final answer